### PR TITLE
EVG-18898 upgrade mongo to 6.0 in testing

### PR DESCRIPTION
**Pull request by ybrill**
[EVG-18898](https://jira.mongodb.org/browse/EVG-18898)

### Description
Shamelessly plagiarize the changes from https://github.com/mongodb/amboy/pull/318/files to upgrade the db to 6.0. Along the way upgrade ubuntu to 22.04

### Testing
♾️

### CODE REVIEW

**Comment by ybrill** [comment]
Added tests from each of the build variants

**Comment by ybrill** [comment]
Borrowed the concept from `wait_for_mongo.js` to try to make `create_auth_user.js` more stable.

**Comment by ybrill** [comment]
`js-test` broke when I updated the distro it was running on. In consultation with @SupaJoon it seems that we'll need to update Karma to get it to work. 
Opened [EVG-19996](https://jira.mongodb.org/browse/EVG-19996) to update Karma. In the meantime, moved it to its own ubuntu2004 variant.

**Comment by ybrill** [comment]
The spruce/parsley tests will be fixed when we merge their PRs ([spruce](https://github.com/evergreen-ci/spruce/pull/1844), [parsley](https://github.com/evergreen-ci/parsley/pull/287)). Once this PR merges those PRs will be clear to merge.

**Review by johndaniels — APPROVED** [review]

**Comment by johndaniels** [comment]
I'm going to steal your variable scheme for the other things that need to download mongosh. Definitely better.

**Pull request merged**
