### PR TITLE
EVG-14197 remove user from log

### PR DESCRIPTION
**Pull request by ablack12**
Super not sure how this panicked but I'm blaming grip?

### CODE REVIEW

**Review by john-m-liu — COMMENTED** [review]
I don't think this fixes it. The problem is this one: https://play.golang.org/p/QsnqyRQ2Yom

I fixed this a couple years back by adding an IsNil function to the interface, but Sam removed it because it was messy. Maybe we could reintroduce that or just leave as is

**Comment by ablack12** [comment]
Oh I see. I'm just going to remove logging the user then, since we've established that many users use this route.

**Review by john-m-liu — APPROVED** [review]

**Comment by ablack12** [comment]
evergreen merge

**Comment by ablack12** [comment]
evergreen merge

**Pull request merged**
