### PR TITLE
EVG-15861 Replace tarjan with fork

### PR DESCRIPTION
**Pull request by bsamek**

### CODE REVIEW

**Comment by bsamek** [comment]
@Kimchelly I'm not sure why the go.sum didn't get edited.

**Comment by Kimchelly** [comment]
The go.sum won't delete `github.com/tychoish/tarjan` until every single dependency that uses it removes it from its go.mod.

Typing `go mod why -m github.com/tychoish/tarjan` says it's anser:
```sh
$ go mod why -m github.com/tychoish/tarjan
# github.com/tychoish/tarjan
github.com/evergreen-ci/evergreen/migrations
github.com/mongodb/anser
github.com/tychoish/tarjan
```

Another similar way to do achieve the above would be this:
```sh
go mod graph | grep github.com/tychoish/tarjan
```

**Comment by bsamek** [comment]
@Kimchelly Ah thanks. Would it be okay to merge this and then a later run of `go mod tidy` would remove it once it's removed from anser? (I can ticket switching it everywhere.)

**Review by Kimchelly — APPROVED** [review]
SGTM

**Comment by bsamek** [comment]
I'm keeping this open for https://github.com/evergreen-ci/certdepot/pull/27

**Pull request merged**
