### PR TITLE
TIG-3231: New trend charts in evergreen

### PR DESCRIPTION
**Pull request by ancostas**
[TIG-3231](https://jira.mongodb.org/browse/TIG-3231)

### Description 
Include the new trend charts on evergreen's task data page.

### Testing 
I have not, since I'm not able to run evergreen locally.

### CODE REVIEW

**Review by ablack12 — COMMENTED** [review]
The js test failure looks relevant, can you take a look?

**Comment by ancostas** [comment]
@ablack12 Yeah, looks like I had to account for task being undefined during testing. Sorry about that!

**Review by ablack12 — APPROVED** [review]
🤞

**Comment by ancostas** [comment]
evergreen merge

**Pull request merged**
