### PR TITLE
EVG-14657: Add test_log route for fetching all logs of a group id

### PR DESCRIPTION
**Pull request by julianedwards**
JIRA: https://jira.mongodb.org/browse/EVG-14657

### CODE REVIEW

**Review by Kimchelly — COMMENTED** [review]
Why do we need 2 routes that do the same thing? Is it because test name is optional?

**Comment by julianedwards** [comment]
The new route actually fetches _all_ test logs for the given taskid/execution. We need this for the job logs page in lobster—it will render all the test logs for the given taskid/execution/group.

**Comment by julianedwards** [comment]
We _can_ make `test_name` a parameter, but then it would cause some backward compatibility issues.

**Review by Kimchelly — APPROVED** [review]
LGTM mod request.

Can you mention the rationale behind this in a comment above the two routes?

**Comment by julianedwards** [comment]
I added a `test_name` param and a note that we are leaving the old route temporarily for backwards compatibility. I changed the legacy UI and the rest model to use the new route. I think we can remove the route after it gets updated in spruce.

I tested in staging and the legacy UI works.

**Review by Kimchelly — APPROVED** [review]

**Pull request merged**
