### PR TITLE
DEVPROD-4517 Add idle lock to host

### PR DESCRIPTION
**Pull request by bynn**
DEVPROD-4517

### Description
To prevent race conditions where the idle host monitor picks up a host while it is in the process of clearing and ending the task it was running, I added a field called "IsIdle" that is set to false when we want to lock the host while we do something that could potentially be slow (like ending a task) 

### Testing
unit test
added sleep 40 seconds to task end to emulate what would happen if it took a long time and it was not picked up by idle host monitor job

### CODE REVIEW

**Review by Kimchelly — COMMENTED** [review]
I didn't read the PR that deeply, but just my $0.02:

Instead of implementing a new lock mechanism (which I think sounds quite risky and could potentially be a source of bugs in itself), did we consider instead investigating what causes slowness in end task and try to improve it? We've typically assumed that end task route runs quickly for performance reasons (otherwise we're wasting money on the host just sitting around waiting for the app server to finish up its work). It used to be fast enough, meaning there wasn't any issue of a race between the idle host termination job and the end task route in the past. I wonder if this solution may be masking over performance issues (and potentially other bugs resulting from the slow performance) in the end task route that we should look into. Just from looking at some stats, the route has become slower than it used to be in the past:
* In [October 2023](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20%2Frest%2Fv2%2Fhosts%2F*%2Ftask%2F*%2Fend%20action%3Dcompleted%20%0A%7C%20stats%20avg(duration_ms)%20p99(duration_ms)%20max(duration_ms)&display.page.search.mode=verbose&dispatch.sample_ratio=10000&workload_pool=standard_perf&earliest=1696132800&latest=1698811200&display.page.search.tab=statistics&display.general.type=statistics&sid=1709153030.3481425), the average runtime of end task was ~475 ms with a p99 of 3.3 seconds and max of 13 seconds (note that the max is under the idle threshold).
* In [February 2024](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20%2Frest%2Fv2%2Fhosts%2F*%2Ftask%2F*%2Fend%20action%3Dcompleted%20%0A%7C%20stats%20avg(duration_ms)%20p99(duration_ms)%20max(duration_ms)&display.page.search.mode=verbose&dispatch.sample_ratio=10000&workload_pool=standard_perf&earliest=1706763600&latest=1709182800&display.page.search.tab=statistics&display.general.type=statistics&sid=1709153275.3482050), the average end task duration is now 1.1 seconds with a p99 of 9.3 seconds and a max of 71 seconds (note that the max is over the idle threshold).

My thought is that investigating the cause of the performance slowdown and trying to improve it if possible would help more than allowing it to be really slow and then trying to work around that slowness.

---

Alternatively, if we still want to go the route of allowing end task to be slow, I wonder if we can instead do it in a less risky way, like recording the last timestamp when a host was still assigned a task (e.g. when `host.ClearRunningAndSetLastTask` was called in end task), and then have the idle timeout job provide an extra long grace period for unusually slow end task requests.

**Review by ablack12 — COMMENTED** [review]
Separately, idk if this lock actually make sense -- we're marking it as idle when that's not accurate. Another idea might be, we assume here that no task is currently assigned [when decommissioning](https://github.com/evergreen-ci/evergreen/blob/fb43d7c7a18cdfe99733f9cbd845aa78204089ef/units/host_termination.go#L232) because we checked running task above; if we don't want to terminate when busy, shouldn't this update fail? Conditionally adding that to the query may help (I think Kim makes a valid point we should look into performance implications but we may want to follow up on that in a separate ticket)

**Comment by Kimchelly** [comment]
@ablack12 I think the issue is that from the idle host job's perspective, the host really has been idle for 30 seconds because it's not assigned any task and the DB suggests it isn't doing anything. For the tasks that had this issue, the host doesn't have any running task assigned because end task [already cleared the host's running task](https://github.com/evergreen-ci/evergreen/blob/42df498806a7683f87d2f8c4f6e61add6b969a91/rest/route/host_agent.go#L1270) and [already set the task's finished status](https://github.com/evergreen-ci/evergreen/blob/22855c4438909b1f7235c58a66fe919d63c6a372/model/task_lifecycle.go#L716). It's the stuff _after_ that line (e.g. updating dependencies, updating builds, stepback, etc.) that's taking >30 seconds to finish.

I did recommend an "add even more idle time after the host's last task" solution, which could work around the fact that the host really looks idle when the stuff after `t.MarkEnd` is really slow.

**Comment by ablack12** [comment]
The DB state _does_ suggest it's doing something though, we just haven't re-checked the DB state, we're relying on an old one from earlier. If we were to re-verify in the query that the DB state is as expected (i.e. that it hasn't been assigned a running task) then this would be consistent and I feel like more accurate than increasing the time to what the length of time we expect the job to run is (although that also seems fine, I just don't see why re-verifying the DB state isn't stronger).

**Comment by Kimchelly** [comment]
I totally agree with you - I think having the update statement still check the running task would be useful as an extra safety measure if the host actually makes it to the next task. But I don't think it'll fully fix all the issues being caused by wrong decommissioning, because the end task slowness is causing the idle host to decommission them, which is causing knock-on issues like events/notifications not being sent. I'm fine with making a separate ticket if we think it's an independent but related bug as long as we clarify that issue of false decommissioning isn't fully fixed after this PR.

**Pull request closed without merging**
