### PR TITLE
EVG-5198: selectively disable task execution on some distros

### PR DESCRIPTION
**Pull request by tychoish**

### CODE REVIEW

**Comment by john-m-liu** [comment]
Is there a functional difference between this and disabling scheduling of it?

**Comment by tychoish** [comment]
this causes the validator to fail *and* prevents the scheduler from running.

**Comment by john-m-liu** [comment]
Can't we change the validator to fail if the existing setting is set then?

**Comment by tychoish** [comment]
I think it's not intuitive that you have to change something in the global configuration to make task dispatching canceled on a given distro. 

I think this is more clear from a proximity perspective, and will also be helpful if we have distro configurations and images that we provide and support for spawn * for tasks (and users!) but don't want tasks to run on.

**Comment by john-m-liu** [comment]
But I'm talking about the flag in the distro config - that seems to be identical to this

**Comment by tychoish** [comment]
I believe that user's can't spawn disabled

**Pull request closed without merging**
