### PR TITLE
EVG-3541: look for a task name ending with _WT if the current task name is not found

### PR DESCRIPTION
**Pull request by jimoleary**
I am not convinced that this is a full fix, but it seems to be enough to get more tasks on the perf discovery page.

### CODE REVIEW

**Comment by jimoleary** [comment]
@bsamek, the data returned for [json/task/sys-perf-4.0/3.6.5-Baseline/linux-1-node-replSet/bestbuy_query/perf](https://evergreen.mongodb.com/plugin/json/tag/sys-perf-4.0/3.6.5-Baseline/linux-1-node-replSet/bestbuy_query/perf) and [json/task/sys_perf_4.0_linux_1_node_replSet_bestbuy_query_8755c4be08d5ba34da5667181f1d1cbb650d7338_18_06_14_14_27_53/perf/](https://evergreen.mongodb.com/plugin/json/task/sys_perf_4.0_linux_1_node_replSet_bestbuy_query_8755c4be08d5ba34da5667181f1d1cbb650d7338_18_06_14_14_27_53/perf/) looks correct (that is neither task name has '_WT' in it).

This change was / is just a work around until the actual issue is found / fixed.

**Comment by unrealsolver** [comment]
@bsamek , my citation from PERF daily doc:

> Task names which are coming from EVG /rest/v1/builds/{version_id} API might be inconsistent (include or does not include _WT/MMAP at the end of the name)
> This could be easily fixed on client-side by normalizing all task names to not have _WT/MMAP at the end of the string. I think EVG will be OK with this solution.

It's pretty similar to Jim's approach, but more transparent and simple.

**Comment by tychoish** [comment]
I don't think its reasonable to merge this in. 

It seems likely that we just need to rename some tasks.

**Comment by dalyd** [comment]
From talking to Jim offline, could we access the data through a different endpoint. It looks like perf discovery is going to a build API endpoint and pulling all the data from there. I don't know where that data comes from. I do know we updated all the documents in the json directory for task names. Could we just query against the json collection based on task name? Especially for the compare to side of things?

**Comment by jimoleary** [comment]
@tychoish now that ruslan has found the issue then that seems reasonable, but now we need to add a new function to [tools.js])https://github.com/10gen/dsi/blob/master/dbtools/tools.js) to rename the _WT tasknames in the builds.

For example, in the [following] (https://evergreen.mongodb.com/rest/v1/builds/sys_perf_linux_1_node_replSet_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26) __bestbuy_agg_WT__ should read __bestbuy_agg__:
```js
{
  "id": "sys_perf_linux_1_node_replSet_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
  "create_time": "2018-05-22T19:12:26.853Z",
  "start_time": "2018-05-22T19:34:16.206Z",
  "finish_time": "2018-05-22T22:32:55.209Z",
  "version": "5b046b9ae3c3310342afae24",
  "project": "sys-perf",
  "revision": "7d71638c84fe95e77e2bdd58cfe117b616aeb31a",
  "variant": "linux-1-node-replSet",
  "number": "14796",
  "status": "failed",
  "activated": true,
  "activated_time": "0001-01-01T00:00:00Z",
  "order": 624,
  "tasks": {
    "bestbuy_agg_MMAPv1": {
      "task_id": "sys_perf_linux_1_node_replSet_bestbuy_agg_MMAPv1_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 3552535171605
    },
    "bestbuy_agg_WT": {
      "task_id": "sys_perf_linux_1_node_replSet_bestbuy_agg_WT_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 3523051782708
    },
    "bestbuy_query_MMAPv1": {
      "task_id": "sys_perf_linux_1_node_replSet_bestbuy_query_MMAPv1_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "failed",
      "time_taken": 3980252839568
    },
    "bestbuy_query_WT": {
      "task_id": "sys_perf_linux_1_node_replSet_bestbuy_query_WT_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 3953432350433
    },
    "change_streams_latency": {
      "task_id": "sys_perf_linux_1_node_replSet_change_streams_latency_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "failed",
      "time_taken": 7549407407996
    },
    "change_streams_throughput": {
      "task_id": "sys_perf_linux_1_node_replSet_change_streams_throughput_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "failed",
      "time_taken": 4576860446240
    },
    "crud_workloads_MMAPv1": {
      "task_id": "sys_perf_linux_1_node_replSet_crud_workloads_MMAPv1_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 2182552751967
    },
    "crud_workloads_WT": {
      "task_id": "sys_perf_linux_1_node_replSet_crud_workloads_WT_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "failed",
      "time_taken": 2415301618172
    },
    "industry_benchmarks_MMAPv1": {
      "task_id": "sys_perf_linux_1_node_replSet_industry_benchmarks_MMAPv1_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 5971195984793
    },
    "industry_benchmarks_WT": {
      "task_id": "sys_perf_linux_1_node_replSet_industry_benchmarks_WT_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 3488743688885
    },
    "map_reduce_workloads_MMAPv1": {
      "task_id": "sys_perf_linux_1_node_replSet_map_reduce_workloads_MMAPv1_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 2464617972349
    },
    "map_reduce_workloads_WT": {
      "task_id": "sys_perf_linux_1_node_replSet_map_reduce_workloads_WT_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 2148964366644
    },
    "misc_workloads_MMAPv1": {
      "task_id": "sys_perf_linux_1_node_replSet_misc_workloads_MMAPv1_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 3395735027164
    },
    "misc_workloads_WT": {
      "task_id": "sys_perf_linux_1_node_replSet_misc_workloads_WT_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "failed",
      "time_taken": 3586271067791
    },
    "mixed_workloads_MMAPv1": {
      "task_id": "sys_perf_linux_1_node_replSet_mixed_workloads_MMAPv1_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 3490336336685
    },
    "mixed_workloads_WT": {
      "task_id": "sys_perf_linux_1_node_replSet_mixed_workloads_WT_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 3936179827423
    },
    "non_sharded_workloads_MMAPv1": {
      "task_id": "sys_perf_linux_1_node_replSet_non_sharded_workloads_MMAPv1_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 2231393183463
    },
    "non_sharded_workloads_WT": {
      "task_id": "sys_perf_linux_1_node_replSet_non_sharded_workloads_WT_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 2451464789083
    },
    "retryable_writes_workloads_WT": {
      "task_id": "sys_perf_linux_1_node_replSet_retryable_writes_workloads_WT_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 4219215320775
    },
    "smoke_test": {
      "task_id": "sys_perf_linux_1_node_replSet_smoke_test_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "success",
      "time_taken": 423002639259
    },
    "snapshot_reads_WT": {
      "task_id": "sys_perf_linux_1_node_replSet_snapshot_reads_WT_patch_7d71638c84fe95e77e2bdd58cfe117b616aeb31a_5b046b9ae3c3310342afae24_18_05_22_19_12_26",
      "status": "failed",
      "time_taken": 1136436710212
    }
  },
  "time_taken": 10719003921171,
  "name": "Linux 1-Node ReplSet",
  "requester": "patch_request"
}
```
My main concerns with changing the field names  of __tasks__ are:
   # mapping field names will be ugly, error prone and slow.
   # it needs to be rerun every time  an old tasks is run.

I think it may be that we need to spend some more time considering alternative solutions (refactoring, new end point, something else) that we can all agree on. But in the meantime perf discovery remains broken.

**Comment by bsamek** [comment]
@dalyd 

> Could we just query against the json collection based on task name? Especially for the compare to side of things?

The available endpoints are here: https://github.com/evergreen-ci/evergreen/blob/master/service/api.go#L732-L736

**Comment by bsamek** [comment]
I'm going to close this, since it sounds like there is a way forward by redoing baselines. We can revisit if needed.

**Pull request closed without merging**
