### PR TITLE
EVG-8111 Not authing against corp secure properly when using performance analysis and triage service

### PR DESCRIPTION
**Pull request by ancostas**
@john-m-liu Relating to the questions asked yesterday. It seems this is sufficient to get the page I care about working; wondering whether this can be done in a better way/if we want to use this corpsecure login more generally in EVG?

### CODE REVIEW

**Comment by john-m-liu** [comment]
So that URL is the okta login page. There should be an active login session already maintained by evergreen. What are you trying to do?

**Comment by ancostas** [comment]
@john-m-liu I want the cookies w/ credentials for reaching out to signal processing service to be present in the browser, so that they get sent for me whenever using this service from the front end.

This is probably simpler than I think, but I'm not sure how to get evergreen to do that for me, so my initial approach is the dumb one and just redirect to login myself.

**Comment by bsamek** [comment]
@ancostas Could you open a ticket to move the constants out of public/static/app/common/constants.js and onto the admin config page?

**Comment by john-m-liu** [comment]
We don't maintain any okta-related tokens in cookies - those are stored in the db. Are you trying to use those credentials to authenticate to Atlas?

**Comment by ancostas** [comment]
@john-m-liu No, just trying to execute a GET request against a service deployed in Kanopy.

**Comment by ancostas** [comment]
@john-m-liu Updated per our discussion -- on connection error to our service in kanopy, we now prompt user to try the login redirect, rather than redirecting them automatically.

**Pull request merged**
