### PR TITLE
EVG-13221: Conditionally unmount a volume before deleting via removeVolume mutation

### PR DESCRIPTION
**Pull request by SupaJoon**
https://jira.mongodb.org/browse/EVG-13221
This prevents the removeVolume mutation from hanging in case the volume is mounted to a host

### CODE REVIEW

**Comment by ablack12** [comment]
With the legacy UI we don't allow users to delete a volume that's attached, because likely that's an accident--they first have to manually unmount it and then they can delete it. I worry that this ticket will open the door for user error, and once the volume is deleted there's not much we can do. I think that deletion just shouldn't be available for mounted volumes, or the user should have to confirm (via modal perhaps?) that they would also like to unmount it.

**Comment by SupaJoon** [comment]
> With the legacy UI we don't allow users to delete a volume that's attached, because likely that's an accident--they first have to manually unmount it and then they can delete it. I worry that this ticket will open the door for user error, and once the volume is deleted there's not much we can do. I think that deletion just shouldn't be available for mounted volumes, or the user should have to confirm (via modal perhaps?) that they would also like to unmount it.

Currently in spruce the user must confirm deletion and unmounting. I thought this could be a helpful addition so the user can delete a mounted volume in 2 clicks instead of 4. 
Screen Shot 2020-11-03 at 1 04 19 PM
Screen Shot 2020-11-03 at 1 05 29 PM

**Comment by ablack12** [comment]
Deleting a mounted volume is likely not a common thing -- Maybe if someone says yes for deleting volume "some new thang" (love that haha) that is attached, there will be an additional prompt that makes sure they're okay with also attaching it? So 3 clicks. Otherwise I think 4 clicks is fine -- we really want to make sure they know what they're doing here.

**Comment by SupaJoon** [comment]
> Deleting a mounted volume on purpose is likely not a common thing -- Maybe if someone says yes for deleting volume "some new thang" (love that haha) that is attached, there will be an additional prompt that makes sure they're okay with also deattaching it? So 3 clicks. Otherwise I think 4 clicks is fine -- we really want to make sure they know what they're doing here.

I think we can meet halfway at 3 clicks. Let me know what you think of this UX. The checkbox will only be visible for volumes that are mounted: 
some new thang gif

**Comment by ablack12** [comment]
That looks good to me, thank you! If we're doing that work as a separate ticket though I think the work here should also hold off, to avoid users making this mistake in the interim.

**Review by khelif96 — APPROVED** [review]

**Comment by SupaJoon** [comment]
I will merge this in after we deploy changes from https://github.com/evergreen-ci/spruce/pull/516

**Pull request merged**
