### PR TITLE
EVG-2444 Specify --index in git apply for patch builds

### PR DESCRIPTION
**Pull request by richardsamuels**

### CODE REVIEW

**Comment by tychoish** [comment]
what kind of test coverage does this code have?

**Comment by richardsamuels** [comment]
@tychoish none. I can add some tests similar to what I did for the clone command

**Comment by tychoish** [comment]
I'm fine with this, but I'd like to run some tests, and also make sure we watch it carefully given that this can run on a myriad of different versions of git

**Comment by tychoish** [comment]
sounds good. do add some automated tests though.

**Comment by richardsamuels** [comment]
@tychoish Actually there was a test, in command/get_patch_test.go. Do you want more than this, like actually running the commands, or are we good to go?

**Pull request merged**
