### PR TITLE
EVG-18538: add admin setting for parser project S3 bucket

### PR DESCRIPTION
**Pull request by Kimchelly**
Jira: https://jira.mongodb.org/browse/EVG-18538

### Description 
Add an admin setting for the S3 bucket name that the app uses to store large parser projects. It's not used for now, since the S3 implementation of parser project access isn't implemented yet.

### Testing 
Updated existing unit tests and tested the admin setting UI in local Evergreen.

### CODE REVIEW

**Review by hadjri — APPROVED** [review]
Will we be adding this to Spruce as well?

**Comment by Kimchelly** [comment]
Does Spruce have an admin UI?

**Comment by malikchaya2** [comment]
> Does Spruce have an admin UI? I thought that was one of the "low priority" pages that won't be migrated for a long time.

not yet

**Comment by hadjri** [comment]
> > Does Spruce have an admin UI? I thought that was one of the "low priority" pages that won't be migrated for a long time.
> 
> not yet

I see, I misunderstood. Thanks!

**Pull request merged**
