### PR TITLE
EVG-14192 upgrade go driver to v1.5.0

### PR DESCRIPTION
**Pull request by john-m-liu**
I can also hold off on this if it'll cause merge conflicts with upgrading to go1.16

### CODE REVIEW

**Comment by ablack12** [comment]
don't tell me what to do

**Review by ablack12 — COMMENTED** [review]
don't tell me what to do

**Review by Kimchelly — APPROVED** [review]
This shouldn't affect go1.16 usage at all.

**Comment by john-m-liu** [comment]
evergreen merge

**Pull request merged**
