### PR TITLE
DEVPROD-11847 remove create version route

### PR DESCRIPTION
**Pull request by ablack12**
DEVPROD-11847

### Description
This route isn't authed strictly enough, allows you to bypass adhoc versions, and use admin only variables.

### Testing
Wrote a test for admin only variables to make sure we think about our requesters and whether they should have admin-only variable access explicitly.

### Documentation
ran swaggo

### CODE REVIEW

**Review by Kimchelly — COMMENTED** [review]
If we do this, we also have to delete `evergreen create-version` since it uses this route.

If we delete, we should aso close DEVPROD-11844 and update the email that was just sent out about `evergreen create-version` since the functionality will not exist anymore.

**Comment by ablack12** [comment]
Oooooof okay Idk why I assumed that used a different endpoint... let me consider bringing it back and just fixing the route, since we just told Trevor about it

**Review by Kimchelly — APPROVED** [review]
The decision making is chaotic but I have no opposition to deleting the feature 😄

**Comment by ablack12** [comment]
apologies for chaos haha

**Pull request merged**
