### PR TITLE
DEVPROD-6086 Improve schedule limit error messages

### PR DESCRIPTION
**Pull request by bynn**
DEVPROD-6086

### Description
scheduling limit error was crowded and convoluted before 

### Testing
Error is more user friendly and clear to read 

image

### CODE REVIEW

**Review by Kimchelly — CHANGES_REQUESTED** [review]
Do we need to shorten the error message? It seems like the proposed solution is a little hacky because it relies on hard-coding the exact error message wrapping text for checking the task scheduling limit, needs to parse the error string and hoping the last error string and doesn't happen to have a semicolon in it. Unless the UI message is somehow unreadable/somehow doesn't have the scheduling limit in it, I kind of feel like it should be clear enough as long as that information is visible, in which case we shouldn't do some special string parsing to try to make the error look better.

Alternatively, if we really want to show a shorter error message, a cleaner way to implement this is that you could define a special error type for the task scheduling limit error, and then use `errors.As` to unwrap the error here, so you can get just the base error message. There's an example of a custom error [here](https://github.com/mongodb/amboy/blob/3b1827bc716865525e0569d5e9186f166303a7bb/errors.go#L23) and [an example of using errors.As](https://github.com/evergreen-ci/cocoa/blob/69a3ef4b69a0964b1f1ac59c613296a06ecaea5a/ecs/client.go#L156-L157).

**Comment by bynn** [comment]
hm, one reason I did it like this is because there's two different errors that this [validating function](https://github.com/evergreen-ci/evergreen/blob/ede684eda6afc822ca667ee24e07f01ac9d963bd/model/user/user.go#L175) could return and I didn't want to write special casing for both. 

image
This is what the error would currently look like without this special casing 
@hadjri and @Kimchelly do you think it makes sense to just keep it this way since it's still readable?

**Review by Kimchelly — COMMENTED** [review]
This doesn't look that different from other error messages that Spruce already emits from the back end, and it does say what the limitation is. I think just keeping the error messages as-is is good enough.

**Review by hadjri — COMMENTED** [review]
While the shortened error message looks cleaner, since the current error does ultimately contain all the necessary information to the user despite being a bit crowded, I suppose not making a code change for this for the sake of maintainability is fine.

**Pull request closed without merging**
