### PR TITLE
DEVPROD-7692 fix volume/host expiration links

### PR DESCRIPTION
**Pull request by ablack12**
DEVPROD-7692 

### Description
These links currently just redirect to spawn/host but better to just point to the right place

### CODE REVIEW

**Review by Kimchelly — COMMENTED** [review]
Did you test this out in staging? I thought that we had to use the UI config's UIv2 URL to redirect to the Spruce page. This page doesn't exist in the legacy UI.

**Comment by ablack12** [comment]
Ah I didn't test this in staging (I was hoping to avoid that since it requires creating a volume and messing with the expiration to trigger an email, but I can do that if you want). I didn't realize we were relying on some old redirect logic though, you're right that it would be using https://evergreen.mongodb.com/spawn/host the way it is now. Updating.

**Review by Kimchelly — APPROVED** [review]
Just reasoning about it seems good enough to me, the link seems to work with spruce.mongodb.com!

Might be slightly weird for people who haven't explicitly opted into redirecting to Spruce, but I'm alright with that since this is a pretty minor feature.

**Comment by ablack12** [comment]
Yeah since the page doesn't exist for legacy I think we can go ahead with enforcing it 👍

**Pull request merged**
