### PR TITLE
EVG-6521: add timestamps to task events

### PR DESCRIPTION
**Pull request by tychoish**

### CODE REVIEW

**Comment by bsamek** [comment]
I think the problem in EVG-6521 is more than that though. There doesn't need to be a date at all, since there's already a date (though from what I don't know).

**Comment by tychoish** [comment]
There are two dates in the task events... because the task event is a nested structure inside of a task wrapper. 

we could also fix this by changing the UI but then it'd be wrong for schedule time.

**Comment by bsamek** [comment]
Screen Shot 2019-08-02 at 11 44 55 AM

I'm saying we just need to stop reporting a second date for priority changed events, since the date in on the left-hand side is correct. I think this is an HTML change, not a data model change.

**Comment by bsamek** [comment]
I think you only need to change this line https://github.com/evergreen-ci/evergreen/blob/4c1863a96f169ca93b791868a42c3564c3d3c9cc/public/static/partials/taskevent.html#L15

**Pull request merged**
