### PR TITLE
EVG-13413 catch alias errors in periodic builds job, fix file fetching

### PR DESCRIPTION
**Pull request by john-m-liu**
The error we were getting was arguably correct since a specific project had specified an alias that selects nothing. I've added some checking to make this more explicit. Also found a slightly related bug where we were using the wrong file for the definition

### CODE REVIEW

**Review by ablack12 — COMMENTED** [review]
Brian merged something today to log what projects are malformed also; probably merge master to make sure this return happens after.

**Comment by john-m-liu** [comment]
oh ha today is full of coincidences. This should fix what he's logging. I'll leave it in in case I missed something

**Review by ablack12 — APPROVED** [review]
Looks good, @bsamek FYI that this is here

**Comment by bsamek** [comment]
> Looks good, @bsamek FYI that this is here

@ablack12 @john-m-liu Thanks!

**Pull request merged**
