### PR TITLE
EVG-12548 Remove half number of tasks max host validation

### PR DESCRIPTION
**Pull request by bsamek**

### CODE REVIEW

**Comment by ybrill** [comment]
why were we validating this to begin with?

**Comment by ybrill** [comment]
It looks like we reference this in the [wiki](https://github.com/evergreen-ci/evergreen/wiki/Project-Files#task-groups)

**Comment by bsamek** [comment]
Thanks @ybrill. I fixed the wiki.

**Comment by bsamek** [comment]
@ybrill I believe this was meant to enforce/encourage people to use task groups to serialize tasks. However, this doesn't really make sense. Users might want the task group behavior of preserving the directory but also be fine with parallelism.

**Comment by ybrill** [comment]
I'm still wondering, though:
> why were we validating this to begin with?

**Pull request merged**
