### PR TITLE
EVG-2416 Remove old ec2 host provider

### PR DESCRIPTION
**Pull request by bsamek**

### CODE REVIEW

**Comment by bsamek** [comment]
Note that the first commit in this PR is reviewable here https://github.com/evergreen-ci/evergreen/pull/585. I kept both in here so that the auto-patch will run correctly.

**Comment by tychoish** [comment]
For safe rollout, does it make sense to: deploy->switch prod distros to use the new provider->then remove?

**Comment by bsamek** [comment]
> For safe rollout, does it make sense to: deploy->switch prod distros to use the new provider->then remove?

I don't think so. We would need to switch them back. With this strategy a deploy is what switches between the two providers. We can switch selected ones to auto.

**Comment by bsamek** [comment]
I rebased the other commit away (since it's merged now).

**Comment by bsamek** [comment]
I force-pushed the rebase, and am going to close the PR without merging, but keep my branch, since I'm blocked on https://jira.mongodb.org/browse/EVG-2614 and switching the distros.

**Pull request closed without merging**
