### PR TITLE
DEVPROD-7736 Remove inline task groups

### PR DESCRIPTION
**Pull request by bynn**
DEVPROD-7736

### Description
this is unused and broken so we are removing it

### CODE REVIEW

**Comment by ZackarySantana** [comment]
We have some more references to task groups in docs/Project-Configuration/Project-Configuration-Files.md here and in a project validator test still [here](https://github.com/bynn/evergreen/blob/b0cc920eee29a14d40842abd333bb35cca707386/validator/project_validator_test.go#L4221) and [here](https://github.com/bynn/evergreen/blob/b0cc920eee29a14d40842abd333bb35cca707386/docs/Project-Configuration/Project-Configuration-Files.md#L245).

**Comment by bynn** [comment]
good catch!

**Review by ablack12 — APPROVED** [review]
Did you re-verify with all-configs that no one is relying on this? (I'm assuming not if we think it's broken but i'd double check)

**Comment by bynn** [comment]
I checked all configs for use of “task_group” (inline) vs “task_groups” and there was no use of it.

**Pull request merged**
