### PR TITLE
EVG-2190 add degraded mode document

### PR DESCRIPTION
**Pull request by john-m-liu**

### CODE REVIEW

**Comment by tychoish** [comment]
- format as restructured text
- use hyphens rather than underscores as word seperators in text documents.
- remove mentions of internal documents/processes (e.g. the developers guide, slack channels, etc.)

**Comment by john-m-liu** [comment]
Addressed

**Comment by tychoish** [comment]
I'd wrap at 72 characters and add some headings.

**Comment by john-m-liu** [comment]
Addressed

**Pull request merged**
