### PR TITLE
EVG-13167 move annotation permission to task

### PR DESCRIPTION
**Pull request by ablack12**
Combined with the [Spruce PR](https://github.com/evergreen-ci/spruce/pull/595)
image

### CODE REVIEW

**Review by khelif96 — COMMENTED** [review]
Can you preserve the old field temporarily so that its backwards compatible. In a follow up PR after both evergreen and spruce are deployed you can remove it.

**Review by malikchaya2 — CHANGES_REQUESTED** [review]
As part of this ticket, we want to edit the logic for displaying the tab, so that we show the tab to everyone who has modify permissions so they can go to the tab and add annotations, even if there are no annotations. 

Since after this we will be showing this tab to people who don't have the build baron enabled, many people will end up seeing and empty "Related Tickets From Jira" table. We want to edit that to only show it if we actually have related tickets to show. 

Also, since we will now show this tab to anyone with modify permissions, we want to show the AddIssue and AddSuspectedIssue buttons even if there are no issues or suspected issues in the list.

**Comment by SupaJoon** [comment]
> As part of this ticket, we want to edit the logic for displaying the tab, so that we show the tab to everyone who has modify permissions so they can go to the tab and add annotations, even if there are no annotations.

I think @ablack12 takes care of this in the [spruce pr](https://github.com/evergreen-ci/spruce/pull/595/files#diff-3b0a7a05ae2803dcb67d915ecfbf574c3a935bfb3fdbaa4c768a248b8b1a7db8R139)

**Comment by malikchaya2** [comment]
> > As part of this ticket, we want to edit the logic for displaying the tab, so that we show the tab to everyone who has modify permissions so they can go to the tab and add annotations, even if there are no annotations.
> 
> I think @ablack12 takes care of this in the [spruce pr](https://github.com/evergreen-ci/spruce/pull/595/files#diff-3b0a7a05ae2803dcb67d915ecfbf574c3a935bfb3fdbaa4c768a248b8b1a7db8R139)

My bad, I meant to leave this comment on the Spruce PR. I believe the other two comments still apply. I will fix this tomorrow.

**Review by malikchaya2 — APPROVED** [review]

**Review by SupaJoon — APPROVED** [review]

**Pull request merged**
