### PR TITLE
Evg 7130 - Adding a tag fails before AWS gives us an instance

### PR DESCRIPTION
**Pull request by malikchaya2**
[EVG-7130](https://jira.mongodb.org/browse/EVG-7130)

While tags can be added to a host that is starting, provisioning, stopping, or stopped, it cannot be added to a host that is still initializing. Attempting to do so causes 500 errors that are confusing to the user. 

I added error prevention, by removing the the option to add a tag while the host is initializing, instead asking the user to wait until it's done. 

Attached are screenshots that show the adding tags card in different host states. 

evg-7130B
evg-7130A

### CODE REVIEW

**Comment by bsamek** [comment]
> Rather than showing some placeholder text, I think it would be better to hide the card entirely. Placeholder text makes sense if there are other interactive elements in the card or if this UI is high-traffic enough that changing the layout will confuse users, but I feel like neither is the case here

I disagree. I think that text of the form "Cannot set tags while host is initializing" might be slightly better placeholder text, but in general hiding an element can be confusing, because a user might go to the page and scratch their head about a missing UI element they've seen before. My general principle is, what's the solution that makes is less likely that someone might ask us on Slack? I think placeholder text is that solution.

**Comment by john-m-liu** [comment]
That's what I alluded to by the UI being high traffic. If users have the layout memorized, then placeholder text makes sense to not confuse them. However I don't think the tags UI is high traffic, and there are only 18 hosts in production that have custom tags set (14 of which are evg team members)

**Comment by malikchaya2** [comment]
I see the merit in both arguments. @john-m-liu and @bsamek, I'll defer to your judgment.

**Comment by bsamek** [comment]
John sold me in person. Let's hide it.

**Comment by malikchaya2** [comment]
Fixed. 
Updated screen shots (run locally): 
status: running
image

status: building
image

status: initializing
image

**Pull request merged**
