### PR TITLE
EVG-14159: Enable duplicate log test names 

### PR DESCRIPTION
**Pull request by julianedwards**
JIRA: https://jira.mongodb.org/browse/EVG-14159

### CODE REVIEW

**Comment by ybrill** [comment]
If the test name is overridden how does the UI get the original name?

**Comment by julianedwards** [comment]
It uses the `display_test_name` from the test result.

**Review by Kimchelly — APPROVED** [review]

**Comment by ybrill** [comment]
Is the `DisplayTestName` guaranteed to be set? (since it's copied from the 'TestFile' if it's unset).

**Comment by julianedwards** [comment]
If it isn't set then we just use `TestName`

**Pull request merged**
