### PR TITLE
EVG-15334: Add collection update for plugins section

### PR DESCRIPTION
**Pull request by hadjri**
[EVG-15334](https://jira.mongodb.org/browse/EVG-15334)

### Description 
In anticipation of a plugin component in the new UI, graphql resolver functions have been modified to accept a modification section for inputs on the plugin section on the frontend.

### Testing 
Added casing on plugin section to existing unit tests for testing save project by section.

### CODE REVIEW

**Review by malikchaya2 — COMMENTED** [review]
I think this might be accidentally linking the wrong ticket. 

Do we have another ticket to add this to the schema and resolvers?

**Comment by ablack12** [comment]
I believe this is https://jira.mongodb.org/browse/EVG-15534.

**Comment by malikchaya2** [comment]
The ticket mentions graphql resolvers. We should either do that as part of this ticket or create another ticket for that work.

**Comment by ablack12** [comment]
For context @hadjri, Chaya is referencing that we need to add these to the graphql schemas (https://github.com/evergreen-ci/evergreen/blob/3a3eb75676e3050eaec0dc04815367bf65b8f2b8/graphql/schema.graphql#L1022 for example, as well as RepoSettings and the corresponding inputs) and probably add a test for this section to the ProjectSettings queries https://github.com/evergreen-ci/evergreen/tree/cbf15a4932a4c82ed2db3a02daf488a03ac0bb47/graphql/tests/projectSettings/queries. This is your first time interacting with a UI side of the codebase; a new ticket to assign to us could be reasonable if that seems like a lot here, or else Chaya can give you a better overview of how we use graphql.

**Comment by malikchaya2** [comment]
> for example, as well as RepoSettings and the corresponding inputs) and probably add a test for this section to the ProjectSettings queries https://github.com/evergreen-ci/evergreen/tree/cbf15a4932a4c82ed2db3a02daf488a03ac0bb47/graphql/tests/projectSettings/queries. This is your first time interacting with a UI side of the codebase; a new ticket to assign to us could be reasonable if that seems like a lot here, or else Chaya can give you a better overview of how we use graphql.

yes, I'd be happy to either provide an overview or take on the work.

**Review by ablack12 — APPROVED** [review]
This LGTM for fixing this function anyway; can make a new PR or a new ticket for the resolver change if you want

**Pull request merged**
