### PR TITLE
EVG-14923: Allow encoded special characters in evergreen URLs

### PR DESCRIPTION
**Pull request by hadjri**
[EVG-14923](https://jira.mongodb.org/browse/EVG-14923)

### Description 
From the linked ticket, users have encountered task not found errors when clicking on the JIRA tickets generated from build failures due to the task name having special characters.  Change has been made to remove special character encoding on these link generating functions to enable special characters in urls

### CODE REVIEW

**Review by ablack12 — COMMENTED** [review]
I'm not convinced this is the right answer. Isn't there a reason why we do this currently? taskLink hasn't been changed in a while but the ticket implies that this has only recently become a problem. Have we looked into what's changed recently / if removing PathEscape will negatively impact other kinds of taskIds? If we do choose to remove this, we'd likely also want to remove it for builds/versions.

**Comment by hadjri** [comment]
> I'm not convinced this is the right answer. Isn't there a reason why we do this currently? taskLink hasn't been changed in a while but the ticket implies that this has only recently become a problem. Have we looked into what's changed recently / if removing PathEscape will negatively impact other kinds of taskIds? If we do choose to remove this, we'd likely also want to remove it for builds/versions.

The breaking change was in the gimlet to allow encoded paths in the url when setting up the initial mux router: https://github.com/evergreen-ci/gimlet/commit/5fbd893c2d4d34fcbbd8e8e9c65810f41a955e66

This caused methods in the middleware to break because gimlet.getVars(r) would now retrieve encoded task Ids, resulting in 404 errors.  There is a comment above getVars in the codebase saying that it returns decoded parameters but that is no longer the case due to the linked change.  Change has been added to decode parameters when calling getVars.

**Review by ablack12 — COMMENTED** [review]
This change makes sense but we can't modify vendored packages within the codebase like this because then we can't update to future revisions of the package. What you'll want to do is create a gimlet PR with these changes (I would request Julian as the reviewer since he has more context here). 
When that's approved, you want to update the gimlet package in `glide.lock` to use this new revision, and then run the command `VENDOR_PKG=github.com/<owner>/<repo> VENDOR_REVISION=abc123 make revendor`. This will update the vendored package up to this revision. Let me know if you have any questions/issues with this process!

**Comment by hadjri** [comment]
> This change makes sense but we can't modify vendored packages within the codebase like this because then we can't update to future revisions of the package. What you'll want to do is create a gimlet PR with these changes (I would request Julian as the reviewer since he has more context here).
> When that's approved, you want to update the gimlet package in `glide.lock` to use this new revision, and then run the command `VENDOR_PKG=github.com/<owner>/<repo> VENDOR_REVISION=abc123 make revendor`. This will update the vendored package up to this revision. Let me know if you have any questions/issues with this process!

Created: https://github.com/evergreen-ci/gimlet/pull/95

**Pull request closed without merging**
