### PR TITLE
EVG-2298 Unify setup/teardown on spawnhosts and builders

### PR DESCRIPTION
**Pull request by bsamek**

### CODE REVIEW

**Comment by bsamek** [comment]
Shouldn't the agents exit?

**Comment by tychoish** [comment]
Do we copy a new agent over in order to do teardown?

**Comment by bsamek** [comment]
After a deploy, hosts should get new agents, and therefore the new teardown code.

**Comment by bsamek** [comment]
I confirmed this works for spawnhosts in staging.

**Pull request merged**
