### PR TITLE
EVG-14886: use default authorization server for Okta

### PR DESCRIPTION
**Pull request by Kimchelly**
Jira: https://jira.mongodb.org/browse/EVG-14866

### Description 
This is identical to #4820, but I reverted to delay the deploy until Monday when we plan to migrate to the new authorization server.

### CODE REVIEW

**Comment by ybrill** [comment]
the files changed look very different in this PR than in #4820

**Comment by Kimchelly** [comment]
I fixed it.

**Review by ybrill — APPROVED** [review]

**Comment by ybrill** [comment]
What's the plan for changing the `Issuer`? 
Is it only read from the db on app restart? (so we'd change it and then deploy)

**Comment by Kimchelly** [comment]
I'm going with the same plan as was going to be this week until MongoDB.live pushed it - update the DB, deploy, log everyone out.

**Comment by ybrill** [comment]
🚀  sounds good

**Pull request merged**
