### PR TITLE
EVG-13386: strict match on patch tasks build variant filter

### PR DESCRIPTION
**Pull request by tgrander**
https://jira.mongodb.org/browse/EVG-13386

### CODE REVIEW

**Review by john-m-liu — CHANGES_REQUESTED** [review]
The ticket wasn't very clear about this, but I think the intent was to still use regex filtering, but surround the search with ^xxxxx$. That way if you type "e2e" it won't match e2e_local, but typing "e2e*" will match. Could you double check?

**Comment by mvankeulen94** [comment]
Yes, the intent of this ticket is for clicking on the e2e_local variant link (for example) to only match e2e_local, and for clicking on any task boxes within the e2e_local variant to only match tasks of that status on e2e_local.

**Comment by mvankeulen94** [comment]
This shouldn't be changing the fuzzy filtering behavior when typing variants / other criteria manually, though. This is specifically for clicking on the links in the left sidebar.

**Comment by john-m-liu** [comment]
I see, in that case I think the implementation is to leave the back-end as-is, but to have the variant links in the sidebar surround the search with a ^$

**Comment by tgrander** [comment]
> I see, in that case I think the implementation is to leave the back-end as-is, but to have the variant links in the sidebar surround the search with a ^$

nice 👍

**Pull request closed without merging**
