### PR TITLE
EVG-9745: create script to upload files to S3

### PR DESCRIPTION
**Pull request by Kimchelly**
JIRA: https://jira.mongodb.org/browse/EVG-9745

### CODE REVIEW

**Comment by john-m-liu** [comment]
so I'm not exactly sure what Brian was envisioning for this, but wouldn't it be easier to assume that the aws cli is in PATH and use that? The difficulty is that you can't view your API key after you generate/configure it, and I don't want to have to steal evergreen's key for this

**Comment by Kimchelly** [comment]
I actually feel like if we're just going to use the AWS default profile, the behavior of this script isn't much different from what you would get if you just used `curator s3 put` to upload your files to S3.

**Comment by bsamek** [comment]
yeah curator s3 put sgtm

**Comment by john-m-liu** [comment]
sgtm as well

**Pull request closed without merging**
