### PR TITLE
EVG-14411 change parser project upserts to replaces

### PR DESCRIPTION
**Pull request by john-m-liu**
this doesn't actually fix the ticket at all but I noticed that adding new fields to the parser project is likely to get missed with the upsert, so I changed it to replace the document

### CODE REVIEW

**Review by ablack12 — COMMENTED** [review]
This does seem crazy haha but I think I did this to replicate how ProjectRefs work. Is there no reason to use $set as opposed to just replacing the documents? I thought there was a reason but i cant think what it would be 😅   In which case we should change that one as well to be consistent.

**Comment by john-m-liu** [comment]
My first thought was that you didn't want to update the config number without being sure that you incremented it, but that's actually one of the fields. I double checked the fields and the only one that's not there is the OomTracker field, but I imagine that was a mistake because it was added after the fact

**Comment by ablack12** [comment]
Can we also change project refs to do replaces then?

**Comment by john-m-liu** [comment]
yep done

**Review by ablack12 — APPROVED** [review]

**Comment by john-m-liu** [comment]
evergreen merge

**Pull request merged**
