### PR TITLE
EVG-16825 Rename self in functions attached to structs

### PR DESCRIPTION
**Pull request by ZackarySantana**
[EVG-16825](https://jira.mongodb.org/browse/EVG-16825)

### Description 
Golang conventions specify that functions attached to structs not label with 'this'/'self'. This is a refactor for functions that currently use self to not.

### Testing 
Unit tests

### CODE REVIEW

**Review by Kimchelly — APPROVED** [review]
This change seems fine. One note (which I don't feel that strongly about) is that usually, the method receiver name is a shorthand few-characters-long variable name rather than just the entire type spelled out as a variable. I'm alright with this as it is though.

**Comment by ZackarySantana** [comment]
I renamed with one letter / shorthands, does that look better?

**Comment by ZackarySantana** [comment]
Screen Shot 2022-08-11 at 1 14 30 PM

I didn't do it for any js file (or that one xml file) because js has a concept/convention of using self

**Review by Kimchelly — APPROVED** [review]
Yes, the change looks good. Thanks for the tech debt cleanup!

**Pull request merged**
