### PR TITLE
EVG-3113 paginate on test

### PR DESCRIPTION
**Pull request by bsamek**

### CODE REVIEW

**Comment by bsamek** [comment]
The first commit was already code reviewed. The second has not been.

**Comment by john-m-liu** [comment]
Can we do this with a find rather than hinting?

**Comment by bsamek** [comment]
> Can we do this with a find rather than hinting?

I don't see a way to support pagination without an aggregation. Do you have a sense of how to you would use a find? And what the advantage would be?

**Comment by john-m-liu** [comment]
The current pipeline only contains match, sort, limit, and project stages all of which should be doable with a find. I personally prefer finds since they're simpler and easier to follow. It's possible one may be faster than the other though

**Comment by bsamek** [comment]
> The current pipeline only contains match, sort, limit, and project stages all of which should be doable with a find. I personally prefer finds since they're simpler and easier to follow. It's possible one may be faster than the other though

In this case it may be more painful than it's worth. Our mgo for doesn't support hints for finds either, and it looks like adding them may be somewhat more complicated.

**Comment by bsamek** [comment]
I switched to using a find.

**Pull request merged**
