### PR TITLE
EVG-7599: allow distro aliases in checking distro permissions

### PR DESCRIPTION
**Pull request by Kimchelly**
JIRA: https://jira.mongodb.org/browse/EVG-7599

This is to handle the fact that a distro might be deleted and then aliased to another distro ID. The permissions to access the old distro should still apply to the aliased one. The working assumption here is that if you delete a distro, it'll have a corresponding alias in exactly one other distro that replaces it.

### CODE REVIEW

**Comment by ablack12** [comment]
Why does this not need to be extended to every distro.FindById?

**Comment by Kimchelly** [comment]
This probably applies to the usages of it in docker but I haven't look at them because they're related to docker parents and I'll have to understand what it's doing first. I made a ticket (https://jira.mongodb.org/browse/EVG-7600) to investigate, but it doesn't affect the distro aliases rollout.

**Comment by john-m-liu** [comment]
I haven't quite understood distro aliases but this is probably the right time to start. Conceptually, is an alias an actual distro (and could function as an independent distro), or is it more a pointer to another distro?

**Comment by Kimchelly** [comment]
It's more like a pointer. For example, my procedure is to delete archlinux-test and add archlinux-test as an alias for archlinux-small.

If you deleted a distro and added it as an alias to multiple different distros, it would be somewhat more ambiguous which distro the alias should refer to.

**Pull request merged**
