### PR TITLE
EVG-2748 Print new version message on stderr

### PR DESCRIPTION
**Pull request by jamesbroadhead**
As the command continues past this warning, it should be on stderr, not stdout

### CODE REVIEW

**Comment by bsamek** [comment]
This won't compile https://evergreen.mongodb.com/task/mci_ubuntu1604_test_operations_617b59720dd4b61932c19ff2559240c4a7ab1c08_18_02_08_18_12_30. I think you want https://golang.org/pkg/fmt/#Fprintf.

**Comment by tychoish** [comment]
Thanks for this! Can we also have an EVG ticket to track this?

**Comment by bsamek** [comment]
I made an EVG ticket and fixed the function name, and will merge when the tests pass.

**Comment by jamesbroadhead** [comment]
^ thanks -- I was planning on coming back to this once I had some spare time. 

(does this repo not have CI? ;) )

**Pull request merged**
