### PR TITLE
EVG-7460 add some logging for github errors

### PR DESCRIPTION
**Pull request by john-m-liu**
splunk logs for the date no longer exist so part of this is speculation

we can't be hitting a duplicate key for the _id because that's an object ID, so that leaves the only possible culprit being the github message ID. Github is probably not sending the same message ID twice, but we shouldn't necessarily rely on that. So my approach is to make the inserting a github intent part idempotent, which should get around a potential race in our code

### CODE REVIEW

**Comment by ybrill** [comment]
I don't understand how would this have caused a duplicate key error on the patch itself. Isn't this just the patch intent?

**Comment by john-m-liu** [comment]
ah I think what you're saying is that in order to hit the "Evergreen error" we saw we would have had to have a valid intent to process right? I wonder if there were 2 separate problems here and I'll keep looking at what can cause the intent processor to hit an error (which may or may not be a duplicate key)

**Comment by ybrill** [comment]
That was what I was saying: we wouldn't send an "Evergreen error status to Github unless we hit an error processing the patch intent.

I don't understand the change in this PR, though. What's wrong with sending GitHub an error if they send a message with a message ID we've seen before?

**Comment by john-m-liu** [comment]
I wasn't able to figure out what could have been the root cause without additional info (the jobs have been TTLed as well)

My intent with this change was to handle if our code somehow raced and tried to insert an intent for the same message more than once, but it's probably better to let these error. I've removed that and added a bit of logging. I think that's all we can do for now and revisit if it happens again

**Review by ybrill — APPROVED** [review]

**Pull request merged**
